### ISSUE TITLE
Colab2 Q3 answer is incorrect

### ISSUE THREAD

**Issue by junhongmit** [luciusssss/CS224W-Colab#3]
In `Question 3: What is the number of edges for the graph (index 200 in the ENZYMES dataset)? (5 points)`, the graph is assumed `undirected`, and the comment said `You should not count an edge twice if the graph is undirected. For example, in an undirected graph G, if two nodes v and u are connected by an edge, this edge should only be counted once.`

So I think the correct way to approach this is to only count the number of edge $(v, w)$ where $v \le w$. This can be easily achieved by:
```
edges = edges[:, edges[0, :] <= edges[1, :]]
```

**Comment by luciusssss** [comment]
Thanks for pointing out my error. I've fixed it.
