### ISSUE TITLE
colab3的message函数写错了捏

### ISSUE THREAD

**Issue by ChenpengZhang** [luciusssss/CS224W-Colab#4]
alpha这个参数写完以后就没用了，后面断掉了。
个人写的正确的：
att_weight = F.leaky_relu(alpha_i + alpha_j, negative_slope=self.negative_slope)
        if ptr:
            att_weight = torch_geometric.utils.softmax(att_weight, ptr=ptr)
        else:
            att_weight = torch_geometric.utils.softmax(att_weight, index=index, num_nodes=size_i)
        att_weight = F.dropout(att_weight, p=self.dropout)
        out = att_weight * x_j

**Comment by luciusssss** [comment]
已修改，多谢指出问题！
